### ISSUE TITLE
BUG: False Positive

### ISSUE THREAD

**Issue by jacksonbrumbaugh** [nakedmcse/AdventOfCode#1]
on line 3 - would return true if input is 1

this is a false positive 

as 1 is NOT a prime number

technically .. for most mathematicians (specifically the number theorists) 1 is in a category all by its lonesome of neither prime nor composite 

but - props for being clever about marking 2 & 3 accurately as primes 

> JackalBruit

**Comment by nakedmcse** [comment]
Added an early return to cover the given of 1 to return false
